version: "3.9"
services:
 web:
    container_name: web
    image: heryfik/web:1.0
    ports:
      - "8888:80"
    depends_on:
      - database
    links:
      - database
 database:
    container_name: database
    image: heryfik/database:1.0
    ports:
      - "3306:3306"